/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.blocks;

import wtf.metio.yosql.codegen.YoSqlVersion;
import com.palantir.javapoet.TypeName;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@DisplayName("DefaultFields")
class DefaultFieldsTest {

    private DefaultFields generator;

    @BeforeEach
    void setUp() {
        generator = new DefaultFields(BlocksObjectMother.annotationGenerator());
    }

    @Test
    @DisplayName("creates fields")
    void shouldCreateField() {
        Assertions.assertEquals("""
                @javax.annotation.processing.Generated(
                    value = "wtf.metio.yosql",
                    comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                )
                private final java.lang.String test;
                """.replace("${version}", YoSqlVersion.VERSION), generator.field(String.class, "test").toString());
    }

    @Test
    @DisplayName("creates fields for TypeNames")
    void shouldCreateFieldWithTypeName() {
        Assertions.assertEquals("""
                @javax.annotation.processing.Generated(
                    value = "wtf.metio.yosql",
                    comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                )
                private final boolean test;
                """.replace("${version}", YoSqlVersion.VERSION), generator.field(TypeName.BOOLEAN, "test").toString());
    }

    @Nested
    @DisplayName("puts a statement into a text block")
    class Initializer {

        @Test
        @DisplayName("so that a backslash stays a backslash")
        void escapesBackslashes() {
            final var initialized = generator.initialize("select * from t where digits ~ '\\d+'").toString();
            Assertions.assertTrue(initialized.contains("'\\\\d+'"),
                    () -> "a lone backslash is an escape sequence in a text block: " + initialized);
        }

        @Test
        @DisplayName("so that a legal escape does not quietly change the query")
        void escapesLegalEscapeSequences() {
            final var initialized = generator.initialize("select * from t where s ~ '\\s+'").toString();
            Assertions.assertTrue(initialized.contains("'\\\\s+'"),
                    () -> "\\s is a space in a text block, so the query would change: " + initialized);
        }

        @Test
        @DisplayName("so that no run of quotes can end it early")
        void escapesQuotes() {
            final var initialized = generator.initialize("select \"\"\" from t").toString();
            Assertions.assertTrue(initialized.contains("\\\"\\\"\\\""),
                    () -> "a run of quotes could close the block: " + initialized);
        }


        @Test
        @DisplayName("so that whitespace inside a literal survives the line ending")
        void keepsTrailingWhitespace() {
            final var initialized = generator.initialize("select 'two  \nlines' from t").toString();
            Assertions.assertTrue(initialized.contains("'two\\s\\s"),
                    () -> "a text block strips trailing whitespace, literal or not: " + initialized);
        }

        @Test
        @DisplayName("and leaves a statement needing none of that alone")
        void leavesPlainStatementsAlone() {
            final var statement = "SELECT raw FROM table WHERE test = ? AND id = ?;";
            Assertions.assertTrue(generator.initialize(statement).toString().contains(statement));
        }

    }

}
