/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.blocks;

import org.junit.jupiter.api.*;
import wtf.metio.yosql.codegen.YoSqlVersion;
import wtf.metio.yosql.internals.testing.configs.AnnotationsConfigurations;
import wtf.metio.yosql.models.configuration.Annotation;
import wtf.metio.yosql.models.configuration.AnnotationMember;

import static wtf.metio.yosql.codegen.logging.LoggingObjectMother.messages;
import static wtf.metio.yosql.codegen.orchestration.OrchestrationObjectMother.executionErrors;

@DisplayName("DefaultAnnotations")
class DefaultAnnotationsTest {

    @Nested
    @DisplayName("what every generated element says about itself")
    class Marker {

        private DefaultAnnotations generator;

        @BeforeEach
        void setUp() {
            generator = new DefaultAnnotations(AnnotationsConfigurations.defaults(), executionErrors(), messages());
        }

        private String expected() {
            return "@javax.annotation.processing.Generated(value = \"wtf.metio.yosql\", comments = \"generated by YoSQL "
                    + YoSqlVersion.VERSION + " - do not modify, this file is rewritten on every build\")";
        }

        @Test
        @DisplayName("names the generator by its fully qualified name, as the annotation asks")
        void shouldAnnotateClasses() {
            Assertions.assertEquals(expected(), generator.generatedClass().iterator().next().toString());
        }

        @Test
        @DisplayName("says the same on a field")
        void shouldAnnotateFields() {
            Assertions.assertEquals(expected(), generator.generatedField().iterator().next().toString());
        }

        @Test
        @DisplayName("says the same on a method")
        void shouldAnnotateMethods() {
            Assertions.assertEquals(expected(), generator.generatedMethod().iterator().next().toString());
        }

        @Test
        @DisplayName("carries no date, so two builds of the same statements agree")
        void shouldCarryNoDate() {
            final var annotation = generator.generatedClass().iterator().next().toString();
            Assertions.assertFalse(annotation.contains("date"), annotation);
        }

        @Test
        @DisplayName("carries the release that wrote the file, which is nowhere else in it")
        void shouldCarryTheVersion() {
            final var annotation = generator.generatedClass().iterator().next().toString();
            Assertions.assertTrue(annotation.contains(YoSqlVersion.VERSION), annotation);
        }

    }

    @Nested
    @DisplayName("")
    class UserGivenAnnotations {

        private DefaultAnnotations generator;

        @BeforeEach
        void setUp() {
            generator = new DefaultAnnotations(AnnotationsConfigurations.defaults(), executionErrors(), messages());
        }

        @Test
        void asAnnotationSpec() {
            // given
            final var annotation = Annotation.builder().setType("com.example.Annotation").build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMember() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder().setKey("value").setValue("test").build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation("test")""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingCustomKey() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder().setKey("random").setValue("test").build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(random = "test")""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMembers() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder().setKey("value").setValue("test").build())
                    .addMembers(AnnotationMember.builder().setKey("another").setValue("value").build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(value = "test", another = "value")""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingBoolType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("true")
                            .setType("boolean")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = true)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingIntType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("123")
                            .setType("int")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 123)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingLongType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("456789")
                            .setType("long")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 456789)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingShortType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("123")
                            .setType("short")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 123)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingByteType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("123")
                            .setType("byte")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 123)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingFloatType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("3.14")
                            .setType("float")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 3.14)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingDoubleType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("3.14")
                            .setType("double")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 3.14)""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithMemberUsingCharType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("a")
                            .setType("char")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation(test = 'a')""", spec.get().toString());
        }

        @Test
        void asAnnotationSpecWithUnguessableType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("")
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isEmpty());
        }

        @Test
        void asAnnotationSpecWithUnguessableMemberType() {
            // given
            final var annotation = Annotation.builder()
                    .setType("com.example.Annotation")
                    .addMembers(AnnotationMember.builder()
                            .setKey("test")
                            .setValue("a")
                            .setType("")
                            .build())
                    .build();

            // when
            final var spec = generator.asAnnotationSpec(annotation);

            // then
            Assertions.assertTrue(spec.isPresent());
            Assertions.assertEquals("""
                    @com.example.Annotation""", spec.get().toString());
        }

    }

}
