load("@bazel_build_process//java:junit5_test.bzl", "junit5_classpath_test", "junit5_test")

junit5_test(
  name = "de.xn__ho_hia.yosql.model.LoggingAPITest",
  deps = [
    "//yosql-core/src/main/java/de/xn__ho_hia/yosql/model:yosql-core-model",
  ],
)
junit5_test(
  name = "de.xn__ho_hia.yosql.model.SqlTypeTest",
  deps = [
    "//yosql-core/src/main/java/de/xn__ho_hia/yosql/model:yosql-core-model",
  ],
)
