version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
    labels:
      - Build :: GitHub
      - Priority :: Low
      - Type :: Task
