/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.dao.jdbc;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import wtf.metio.yosql.codegen.api.RxJavaMethodGenerator;
import wtf.metio.yosql.codegen.tck.RxJavaMethodGeneratorTCK;
import wtf.metio.yosql.testing.configs.Java;

@DisplayName("JdbcRxJavaMethodGenerator")
class JdbcRxJavaMethodGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.defaults());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final var connection = dataSource.getConnection();
                          final var query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final var rawQuery = QUERY_DATA_RAW;
                          final var index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final var statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final var resultSet = statement.executeQuery();
                          final var resultSetMetaData = resultSet.getMetaData();
                          final var columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 4 configuration")
    class Java4 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java4());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final java.sql.Connection connection = dataSource.getConnection();
                          final java.lang.String query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final java.lang.String rawQuery = QUERY_DATA_RAW;
                          final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final java.sql.ResultSet resultSet = statement.executeQuery();
                          final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                          final int columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 5 configuration")
    class Java5 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java5());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final java.sql.Connection connection = dataSource.getConnection();
                          final java.lang.String query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final java.lang.String rawQuery = QUERY_DATA_RAW;
                          final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final java.sql.ResultSet resultSet = statement.executeQuery();
                          final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                          final int columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 7 configuration")
    class Java7 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java7());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final java.sql.Connection connection = dataSource.getConnection();
                          final java.lang.String query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final java.lang.String rawQuery = QUERY_DATA_RAW;
                          final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final java.sql.ResultSet resultSet = statement.executeQuery();
                          final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                          final int columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 8 configuration")
    class Java8 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java8());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final java.sql.Connection connection = dataSource.getConnection();
                          final java.lang.String query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final java.lang.String rawQuery = QUERY_DATA_RAW;
                          final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final java.sql.ResultSet resultSet = statement.executeQuery();
                          final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                          final int columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 9 configuration")
    class Java9 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java9());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final java.sql.Connection connection = dataSource.getConnection();
                          final java.lang.String query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final java.lang.String rawQuery = QUERY_DATA_RAW;
                          final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final java.sql.ResultSet resultSet = statement.executeQuery();
                          final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                          final int columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 11 configuration")
    class Java11 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java11());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final var connection = dataSource.getConnection();
                          final var query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final var rawQuery = QUERY_DATA_RAW;
                          final var index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final var statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final var resultSet = statement.executeQuery();
                          final var resultSetMetaData = resultSet.getMetaData();
                          final var columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 14 configuration")
    class Java14 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java14());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final var connection = dataSource.getConnection();
                          final var query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final var rawQuery = QUERY_DATA_RAW;
                          final var index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final var statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final var resultSet = statement.executeQuery();
                          final var resultSetMetaData = resultSet.getMetaData();
                          final var columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 16 configuration")
    class Java16 implements RxJavaMethodGeneratorTCK {

        @Override
        public RxJavaMethodGenerator generator() {
            return JdbcObjectMother.rxJavaMethodGenerator(Java.java16());
        }

        @Override
        public String rxJavaReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateRxJavaApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final io.reactivex.Flowable<com.example.util.ResultRow> queryDataFlow(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataFlow");
                      return io.reactivex.Flowable.generate(new java.util.concurrent.Callable<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final com.example.persistence.util.FlowState call() throws java.lang.Exception {
                          final var connection = dataSource.getConnection();
                          final var query = QUERY_DATA;
                          LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                          final var rawQuery = QUERY_DATA_RAW;
                          final var index = QUERY_DATA_INDEX;
                          LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                          final var statement = connection.prepareStatement(query);
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          final var resultSet = statement.executeQuery();
                          final var resultSetMetaData = resultSet.getMetaData();
                          final var columnCount = resultSetMetaData.getColumnCount();
                          return new com.example.persistence.util.FlowState(connection, statement, resultSet, resultSetMetaData, columnCount);
                        }
                      }, new io.reactivex.functions.BiConsumer<com.example.persistence.util.FlowState, io.reactivex.Emitter<com.example.util.ResultRow>>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state,
                            final io.reactivex.Emitter<com.example.util.ResultRow> emitter) throws java.lang.Exception {
                          try {
                            if (state.next()) {
                              emitter.onNext(resultRow.apply(state));
                            } else {
                              emitter.onComplete();
                            }
                          }
                          catch (final java.sql.SQLException exception) {
                            emitter.onError(exception);
                          }
                        }
                      }, new io.reactivex.functions.Consumer<com.example.persistence.util.FlowState>() {
                        @java.lang.Override
                        @javax.annotation.processing.Generated(
                            value = "YoSQL",
                            comments = "DO NOT MODIFY - automatically generated by YoSQL"
                        )
                        public final void accept(final com.example.persistence.util.FlowState state) throws
                            java.lang.Exception {
                          state.close();
                        }
                      });
                    }
                    """;
        }

    }

}
