/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.dao.jdbc;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import wtf.metio.yosql.codegen.api.Java8StreamMethodGenerator;
import wtf.metio.yosql.codegen.tck.Java8StreamMethodGeneratorTCK;
import wtf.metio.yosql.testing.configs.JavaConfigurations;

@DisplayName("JdbcJava8StreamMethodGenerator")
class JdbcJava8StreamMethodGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.defaults());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final var connection = dataSource.getConnection();
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final var statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final var executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final var resultSet = statement.executeQuery();
                        final var resultSetMetaData = resultSet.getMetaData();
                        final var columnCount = resultSetMetaData.getColumnCount();
                        final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 4 configuration")
    class Java4 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java4());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final java.sql.Connection connection = dataSource.getConnection();
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final java.lang.String executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final java.sql.ResultSet resultSet = statement.executeQuery();
                        final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                        final int columnCount = resultSetMetaData.getColumnCount();
                        final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }
    }

    @Nested
    @DisplayName("using JavaConfigurations 5 configuration")
    class Java5 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java5());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final java.sql.Connection connection = dataSource.getConnection();
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final java.lang.String executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final java.sql.ResultSet resultSet = statement.executeQuery();
                        final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                        final int columnCount = resultSetMetaData.getColumnCount();
                        final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 7 configuration")
    class Java7 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java7());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final java.sql.Connection connection = dataSource.getConnection();
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final java.lang.String executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final java.sql.ResultSet resultSet = statement.executeQuery();
                        final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                        final int columnCount = resultSetMetaData.getColumnCount();
                        final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 8 configuration")
    class Java8 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java8());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final java.sql.Connection connection = dataSource.getConnection();
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final java.lang.String executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final java.sql.ResultSet resultSet = statement.executeQuery();
                        final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                        final int columnCount = resultSetMetaData.getColumnCount();
                        final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }
    }

    @Nested
    @DisplayName("using JavaConfigurations 9 configuration")
    class Java9 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java9());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final java.sql.Connection connection = dataSource.getConnection();
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final java.sql.PreparedStatement statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final java.lang.String executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final java.sql.ResultSet resultSet = statement.executeQuery();
                        final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                        final int columnCount = resultSetMetaData.getColumnCount();
                        final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.converter.ResultState state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 11 configuration")
    class Java11 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java11());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final var connection = dataSource.getConnection();
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final var statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final var executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final var resultSet = statement.executeQuery();
                        final var resultSetMetaData = resultSet.getMetaData();
                        final var columnCount = resultSetMetaData.getColumnCount();
                        final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 14 configuration")
    class Java14 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java14());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final var connection = dataSource.getConnection();
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final var statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final var executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final var resultSet = statement.executeQuery();
                        final var resultSetMetaData = resultSet.getMetaData();
                        final var columnCount = resultSetMetaData.getColumnCount();
                        final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

    @Nested
    @DisplayName("using JavaConfigurations 16 configuration")
    class Java16 implements Java8StreamMethodGeneratorTCK {

        @Override
        public Java8StreamMethodGenerator generator() {
            return JdbcObjectMother.java8StreamMethodGenerator(JavaConfigurations.java16());
        }

        @Override
        public String streamLazyReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamLazyApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamLazy(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamLazy");
                      try {
                        final var connection = dataSource.getConnection();
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        final var statement = connection.prepareStatement(query);
                        for (final int jdbcIndex : index.get("test")) {
                          statement.setObject(jdbcIndex, test);
                        }
                        for (final int jdbcIndex : index.get("id")) {
                          statement.setObject(jdbcIndex, id);
                        }
                        if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                          final var executedQuery = rawQuery
                            .replace(":test", test == null ? "null" : test.toString())
                            .replace(":id", java.lang.String.valueOf(id));
                          LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                        }
                        final var resultSet = statement.executeQuery();
                        final var resultSetMetaData = resultSet.getMetaData();
                        final var columnCount = resultSetMetaData.getColumnCount();
                        final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                        return java.util.stream.StreamSupport.stream(new java.util.Spliterators.AbstractSpliterator<com.example.util.ResultRow>(java.lang.Long.MAX_VALUE, java.util.Spliterator.ORDERED) {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final boolean tryAdvance(
                              final java.util.function.Consumer<? super com.example.util.ResultRow> action) {
                            try {
                              if (state.next()) {
                                action.accept(resultRow.apply(state));
                                return true;
                              }
                              return false;
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        }, false).onClose(new java.lang.Runnable() {
                          @java.lang.Override
                          @javax.annotation.processing.Generated(
                              value = "YoSQL",
                              comments = "DO NOT MODIFY - automatically generated by YoSQL"
                          )
                          public final void run() {
                            try {
                              resultSet.close();
                              statement.close();
                              connection.close();
                            }
                            catch (final java.sql.SQLException exception) {
                              throw new java.lang.RuntimeException(exception);
                            }
                          }
                        });
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

        @Override
        public String streamEagerReadMethodExpectation() {
            return """
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateStreamEagerApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.stream.Stream<com.example.util.ResultRow> queryDataStreamEager(
                        final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryDataStreamEager");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.converter.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list.stream();
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """;
        }

    }

}
