/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.dao.jdbc;

import org.junit.jupiter.api.*;
import wtf.metio.yosql.codegen.api.BlockingMethodGenerator;
import wtf.metio.yosql.testing.configs.Java;
import wtf.metio.yosql.testing.configs.Sql;

@DisplayName("JdbcBlockingMethodGenerator")
class JdbcBlockingMethodGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.defaults());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 4 configuration")
    class Java4 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java4());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.CallableStatement statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 5 configuration")
    class Java5 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java5());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.CallableStatement statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 7 configuration")
    class Java7 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java7());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.CallableStatement statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 8 configuration")
    class Java8 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java8());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.CallableStatement statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 9 configuration")
    class Java9 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java9());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final java.sql.Connection connection = dataSource.getConnection()) {
                        final java.lang.String query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final java.lang.String rawQuery = QUERY_DATA_RAW;
                        final java.util.Map<java.lang.String, int[]> index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final java.sql.CallableStatement statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final java.lang.String executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final java.sql.ResultSet resultSet = statement.executeQuery()) {
                            final java.sql.ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
                            final int columnCount = resultSetMetaData.getColumnCount();
                            final com.example.persistence.util.ResultState state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final java.util.List<com.example.util.ResultRow> list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 11 configuration")
    class Java11 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java11());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 14 configuration")
    class Java14 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java14());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

    @Nested
    @DisplayName("using java 16 configuration")
    class Java16 {

        private BlockingMethodGenerator generator;

        @BeforeEach
        void setup() {
            generator = JdbcObjectMother.blockingMethodGenerator(Java.java16());
        }

        @Test
        void shouldGenerateBlockingReadMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingReadMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingWriteMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final int queryData(final java.lang.Object test, final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareStatement(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          return statement.executeUpdate();
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingWriteMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

        @Test
        void shouldGenerateBlockingCallMethod() {
            Assertions.assertEquals("""
                    /**
                     * <p>Executes the following statement:</p>
                     * <pre>
                     * SELECT raw FROM table WHERE test = ? AND id = ?;</pre>
                     *
                     * <p>Generated based on the following file(s):</p>
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     * <p>Disable generating this method by setting <strong>generateBlockingApi</strong> to <strong>false</strong></p>
                     *
                     * @see com.example.util.ResultRow
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public final java.util.List<com.example.util.ResultRow> queryData(final java.lang.Object test,
                        final int id) {
                      LOG.entering("com.example.persistence.DataRepository", "queryData");
                      try (final var connection = dataSource.getConnection()) {
                        final var query = QUERY_DATA;
                        LOG.finer(() -> java.lang.String.format("Picked query [%s]", "QUERY_DATA"));
                        final var rawQuery = QUERY_DATA_RAW;
                        final var index = QUERY_DATA_INDEX;
                        LOG.finer(() -> java.lang.String.format("Picked index [%s]", "QUERY_DATA_INDEX"));
                        try (final var statement = connection.prepareCall(query)) {
                          for (final int jdbcIndex : index.get("test")) {
                            statement.setObject(jdbcIndex, test);
                          }
                          for (final int jdbcIndex : index.get("id")) {
                            statement.setObject(jdbcIndex, id);
                          }
                          if (LOG.isLoggable(java.util.logging.Level.FINE)) {
                            final var executedQuery = rawQuery
                              .replace(":test", test == null ? "null" : test.toString())
                              .replace(":id", java.lang.String.valueOf(id));
                            LOG.fine(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                          }
                          try (final var resultSet = statement.executeQuery()) {
                            final var resultSetMetaData = resultSet.getMetaData();
                            final var columnCount = resultSetMetaData.getColumnCount();
                            final var state = new com.example.persistence.util.ResultState(resultSet, resultSetMetaData, columnCount);
                            final var list = new java.util.ArrayList<com.example.util.ResultRow>();
                            while (state.next()) {
                              list.add(resultRow.apply(state));
                            }
                            return list;
                          }
                        }
                      }
                      catch (final java.sql.SQLException exception) {
                        throw new java.lang.RuntimeException(exception);
                      }
                    }
                    """, generator.blockingCallMethod(Sql.sqlConfiguration(), Sql.sqlStatements()).toString());
        }

    }

}
