/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.codegen.api;

import com.squareup.javapoet.TypeName;
import wtf.metio.yosql.models.immutables.SqlConfiguration;

/**
 * Controls how methods handle exceptions.
 */
public interface MethodExceptionHandler {

    /**
     * Controls which exceptions are thrown from a method generated by the given SQL configuration.
     *
     * @param configuration The given configuration.
     * @return All thrown exceptions.
     */
    Iterable<? extends TypeName> thrownExceptions(SqlConfiguration configuration);

}
