/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: CC0-1.0
 */

package wtf.metio.yosql.codegen.dao;

import com.squareup.javapoet.TypeName;
import wtf.metio.yosql.models.immutables.SqlConfiguration;

/**
 * Controls how methods handle exceptions.
 */
public interface MethodExceptionHandler {

    /**
     * Controls which exceptions are thrown from a method generated by the given SQL configuration.
     *
     * @param configuration The given configuration.
     * @return All thrown exceptions.
     */
    Iterable<? extends TypeName> thrownExceptions(SqlConfiguration configuration);

    /**
     * Controls which exception is thrown for a converter method.
     *
     * @return The thrown exception.
     */
    TypeName thrownException();

}
