/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.example.common;

import org.immutables.value.Value;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.stream.Stream;

/**
 * The six shapes no other example ran.
 *
 * <p>A statement's type and its returning mode pick which method the generator writes, and the
 * examples between them reached seven of the twelve combinations — the seven that happened to be
 * useful for demonstrating something else. The other five were generated by nobody and run by
 * nothing, which is exactly where four of them turned out to emit Java that does not compile.</p>
 *
 * <p>Compiling them is now covered by a test that hands javac every combination. This is the other
 * half: the two failures that compile perfectly and only a database can show — a cursor handing
 * back a stream over resources it already closed, and a write executed twice because the rows were
 * fetched with a second round trip instead of read from the first.</p>
 */
@Value.Immutable
public interface ReturningModeTests {

    static ImmutableReturningModeTests.QueryCompaniesWithoutResultBuildStage builder() {
        return ImmutableReturningModeTests.builder();
    }

    /** reading + none */
    Consumer<String> queryCompaniesWithoutResult();

    /** calling + none */
    Runnable callRandomNumberWithoutResult();

    /** calling + multiple */
    Supplier<List<Map<String, Object>>> callNamesAsList();

    /** calling + cursor */
    Supplier<Stream<Map<String, Object>>> callNamesAsStream();

    /** writing + single */
    BiFunction<Integer, String, Optional<Map<String, Object>>> insertCompanyReturningRow();

    /** writing + multiple */
    BiFunction<Integer, String, List<Map<String, Object>>> insertCompanyReturningRows();

    /** writing + cursor */
    BiFunction<Integer, String, Stream<Map<String, Object>>> insertCompanyReturningStream();

    /** How many companies there are, so that a write can be counted rather than trusted. */
    Supplier<List<Map<String, Object>>> queryAllCompanies();

    @Value.Lazy
    default void runReturningModeTests() {
        try {
            queryCompaniesWithoutResult().accept("one");
            callRandomNumberWithoutResult().run();

            Verify.equal(1, callNamesAsList().get().size(), "a call returning many rows read as a list");

            // Consumed after the method has returned, which is the whole point of a cursor: the
            // stream owns the connection, the statement and the result set until it is closed.
            // Closing them on the way out left the caller a stream over a closed ResultSet.
            try (final var names = callNamesAsStream().get()) {
                Verify.equal(1, names.toList().size(), "a call read one row at a time");
            }

            final var before = queryAllCompanies().get().size();

            final var single = insertCompanyReturningRow().apply(69, "sixtynine");
            Verify.that(single.isPresent(), "a write answering with one row answers");
            Verify.equal("sixtynine", single.orElseThrow().get("NAME"), "and it is the row written");

            final var written = insertCompanyReturningRows().apply(70, "seventy");
            Verify.equal(1, written.size(), "a write answers with the row it wrote");
            Verify.equal("seventy", written.getFirst().get("NAME"), "and it is the row that was written");
            Verify.equal(before + 2, queryAllCompanies().get().size(), "each write inserted one row");

            // The same check for the cursor, and the one that matters most: fetching the rows with
            // a second execute() rather than reading the first one's result inserted the row twice,
            // which compiles, runs, and is only visible by counting.
            try (final var streamed = insertCompanyReturningStream().apply(71, "seventyone")) {
                Verify.equal(1, streamed.toList().size(), "a streaming write answers with its row");
            }
            Verify.equal(before + 3, queryAllCompanies().get().size(), "the streaming write also inserted once");
        } catch (final RuntimeException exception) {
            throw new IllegalStateException("Error while running RETURNING MODE tests", exception);
        }
    }

}
