java_library(
    name = "loggers",
    srcs = [
        "Generator.java",
        "Parser.java",
        "Reader.java",
        "Timer.java",
        "Utilities.java",
        "Writer.java",
    ],
    visibility = [
        "//yosql-benchmarks/src/main/java/wtf/metio/yosql/benchmark:__subpackages__",
        "//yosql-core/src/main/java/wtf/metio/yosql/dagger:__pkg__",
        "//yosql-core/src/main/java/wtf/metio/yosql/generator:__subpackages__",
        "//yosql-core/src/main/java/wtf/metio/yosql/parser:__pkg__",
        "//yosql-core/src/main/java/wtf/metio/yosql/utils:__pkg__",
    ],
    deps = [
        "@maven//:javax_inject_javax_inject",
    ],
)
