[libraries]
hikari = "com.zaxxer:HikariCP:latest.release"
h2 = "com.h2database:h2:latest.release"
rxjava = "io.reactivex.rxjava2:rxjava:latest.release"

[bundles]
database = ["hikari", "h2"]
reactive = ["rxjava"]
