filegroup(
  name = "cli-events",
  visibility = ["//yosql-cli:__subpackages__"],
  srcs = ["cli-events_en.properties"],
)
filegroup(
  name = "commands",
  visibility = ["//yosql-cli:__subpackages__"],
  srcs = ["commands_en.properties"],
)