/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.models.meta.data;

import com.squareup.javapoet.*;
import wtf.metio.yosql.internals.javapoet.TypicalTypes;
import wtf.metio.yosql.models.configuration.Annotation;
import wtf.metio.yosql.models.configuration.AnnotationMember;
import wtf.metio.yosql.models.configuration.GeneratedAnnotationApis;
import wtf.metio.yosql.models.configuration.GeneratedAnnotationMembers;
import wtf.metio.yosql.models.meta.ConfigurationExample;
import wtf.metio.yosql.models.meta.ConfigurationGroup;
import wtf.metio.yosql.models.meta.ConfigurationSetting;

import javax.lang.model.element.Modifier;
import java.util.Collection;
import java.util.List;
import java.util.stream.Stream;

import static wtf.metio.yosql.internals.jdk.Strings.upperCase;

public final class Annotations extends AbstractConfigurationGroup {

    private static final String DEFAULT_COMMENT = "DO NOT MODIFY - automatically generated by YoSQL";
    private static final GeneratedAnnotationMembers DEFAULT_MEMBERS = GeneratedAnnotationMembers.WITHOUT_DATE;
    private static final String ANNOTATION_SPEC = "AnnotationSpec";
    private static final ClassName MAVEN_ANNOTATION_TYPE = mavenType(ANNOTATION_SPEC);
    private static final ClassName GRADLE_ANNOTATION_TYPE = gradleType(ANNOTATION_SPEC);
    private static final String ANNOTATION_MEMBER_SPEC = "AnnotationMemberSpec";
    private static final ClassName MAVEN_MEMBER_TYPE = mavenType(ANNOTATION_MEMBER_SPEC);
    private static final ClassName GRADLE_MEMBER_TYPE = gradleType(ANNOTATION_MEMBER_SPEC);
    private static final String AS_ANNOTATION = "asAnnotation";
    private static final String AS_ANNOTATION_MEMBER = "asAnnotationMember";
    private static final String TYPE = "type";
    private static final String MEMBERS = "members";
    private static final String KEY = "key";
    private static final String VALUE = "value";

    public static ConfigurationGroup configurationGroup() {
        return ConfigurationGroup.builder()
                .setName(Annotations.class.getSimpleName())
                .setDescription("Configures how annotations are applied to the generated code.")
                .addSettings(annotationApi())
                .addSettings(annotateClasses())
                .addSettings(annotateFields())
                .addSettings(annotateMethods())
                .addSettings(classMembers())
                .addSettings(fieldMembers())
                .addSettings(methodMembers())
                .addSettings(classComment())
                .addSettings(fieldComment())
                .addSettings(methodComment())
                .addSettings(generatorName())
                .addSettings(repositoryAnnotations())
                .addSettings(constructorAnnotations())
                .addSettings(methodAnnotations())
                .addMavenTypes(mavenAnnotationSpecType(), mavenAnnotationMemberSpecType())
                .setMavenMethods(List.of(createMavenAnnotations()))
                .addGradleTypes(gradleAnnotationSpecType(), gradleAnnotationMemberSpecType())
                .setGradleMethods(List.of(createGradleAnnotations()))
                .build();
    }

    private static ConfigurationSetting annotationApi() {
        return ConfigurationSetting.builder()
                .setName("annotationApi")
                .setDescription("The annotation API to use.")
                .setType(TypeName.get(GeneratedAnnotationApis.class))
                .setValue(GeneratedAnnotationApis.PROCESSING_API)
                .addExamples(ConfigurationExample.builder()
                        .setValue("PROCESSING_API")
                        .setDescription("The default value of the `annotationApi` configuration option is `PROCESSING_API`. Setting the option to `PROCESSING_API` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;

                                import javax.annotation.processing.Generated;

                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {

                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;

                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                        // ... some code
                                    }

                                    // ... rest of generated code

                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("ANNOTATION_API")
                        .setDescription("Changing the `annotationApi` configuration option to `ANNOTATION_API` uses the annotation API instead.")
                        .setResult("""
                                package com.example.persistence;

                                import javax.annotation.Generated;

                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {

                                    @Generated(
                                          value = "YoSQL",
                                          date = "<current_timestamp>",
                                          comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;

                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                      // ... some code
                                    }

                                    // ... rest of generated code (same as above)

                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting annotateClasses() {
        return ConfigurationSetting.builder()
                .setName("annotateClasses")
                .setDescription("Controls whether Generated annotations should be added to the generated classes.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.CLASSES)
                .addExamples(ConfigurationExample.builder()
                        .setValue("false")
                        .setDescription("The default value of the `annotateClasses` configuration option is `false`. Setting the option to `false` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;

                                public class SomeRepository {

                                    // ... rest of generated code

                                }
                                """)
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("true")
                        .setDescription("Changing the `annotateClasses` configuration option to `true` adds the `@Generated` annotation to every generated classes. Its is possible to configure each value individually using other config options.")
                        .setResult("""
                                package com.example.persistence;

                                import javax.annotation.processing.Generated;

                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {

                                    // ... rest of generated code (same as above)

                                }
                                """)
                        .build())
                .build();
    }

    private static ConfigurationSetting annotateFields() {
        return ConfigurationSetting.builder()
                .setName("annotateFields")
                .setDescription("Controls whether Generated annotations should be added to the generated fields.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.FIELDS)
                .addExamples(ConfigurationExample.builder()
                        .setValue("false")
                        .setDescription("The default value of the `annotateFields` configuration option is `false`. Setting the option to `false` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;

                                public class SomeRepository {

                                    private Object someField;

                                    // ... rest of generated code

                                }
                                """)
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("true")
                        .setDescription("Changing the `annotateFields` configuration option to `true` adds the `@Generated` annotation to every generated fields. Its is possible to configure each value individually using other config options.")
                        .setResult("""
                                package com.example.persistence;

                                import javax.annotation.processing.Generated;

                                public class SomeRepository {

                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;

                                    // ... rest of generated code (same as above)

                                }
                                """)
                        .build())
                .build();
    }

    private static ConfigurationSetting annotateMethods() {
        return ConfigurationSetting.builder()
                .setName("annotateMethods")
                .setDescription("Controls whether Generated annotations should be added to the generated methods.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.METHODS)
                .addExamples(ConfigurationExample.builder()
                        .setValue("false")
                        .setDescription("The default value of the `annotateMethods` configuration option is `false`. Setting the option to `false` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;

                                public class SomeRepository {

                                    public void someMethod() {
                                        // ... some code
                                    }

                                    // ... rest of generated code

                                }
                                """)
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("true")
                        .setDescription("Changing the `annotateMethods` configuration option to `true` adds the `@Generated` annotation to every generated methods. Its is possible to configure each value individually using other config options.")
                        .setResult("""
                                package com.example.persistence;

                                import javax.annotation.processing.Generated;

                                public class SomeRepository {

                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                      // ... some code
                                    }

                                    // ... rest of generated code (same as above)

                                }
                                """)
                        .build())
                .build();
    }

    private static ConfigurationSetting classMembers() {
        return ConfigurationSetting.builder()
                .setName("classMembers")
                .setDescription("The annotation members to use for classes.")
                .setType(TypeName.get(GeneratedAnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .addExamples(ConfigurationExample.builder()
                        .setValue("WITHOUT_DATE")
                        .setDescription("The default value of the `classMembers` configuration option is `WITHOUT_DATE`. Setting the option to `WITHOUT_DATE` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    value = "YoSQL",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("ALL")
                        .setDescription("Changing the `classMembers` configuration option to `ALL` outputs all annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {
                                                                
                                  // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("NONE")
                        .setDescription("Changing the `classMembers` configuration option to `NONE` outputs no annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated
                                public class SomeRepository {
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("VALUE")
                        .setDescription("Changing the `classMembers` configuration option to `VALUE` outputs only the `value` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    value = "YoSQL"
                                )
                                public class SomeRepository {
                                                                
                                  // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("DATE")
                        .setDescription("Changing the `classMembers` configuration option to `DATE` outputs only the `date` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    date = "<current_timestamp>"
                                )
                                public class SomeRepository {
                                                                
                                  // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("COMMENT")
                        .setDescription("Changing the `classMembers` configuration option to `COMMENT` outputs only the `comment` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    comment = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {
                                                                
                                  // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting fieldMembers() {
        return ConfigurationSetting.builder()
                .setName("fieldMembers")
                .setDescription("The annotation members to use for fields.")
                .setType(TypeName.get(GeneratedAnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .addExamples(ConfigurationExample.builder()
                        .setValue("WITHOUT_DATE")
                        .setDescription("The default value of the `fieldMembers` configuration option is `WITHOUT_DATE`. Setting the option to `WITHOUT_DATE` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;
                                   
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("ALL")
                        .setDescription("Changing the `fieldMembers` configuration option to `ALL` outputs all annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("NONE")
                        .setDescription("Changing the `fieldMembers` configuration option to `NONE` outputs no annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                  @Generated
                                  private Object someField;
                                                                
                                  // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("VALUE")
                        .setDescription("Changing the `fieldMembers` configuration option to `VALUE` outputs only the `value` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                  @Generated(
                                      value = "YoSQL"
                                  )
                                  private Object someField;
                                                                
                                  // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("DATE")
                        .setDescription("Changing the `fieldMembers` configuration option to `DATE` outputs only the `date` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                  @Generated(
                                      date = "<current_timestamp>"
                                  )
                                  private Object someField;
                                                                
                                  // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("COMMENT")
                        .setDescription("Changing the `fieldMembers` configuration option to `COMMENT` outputs only the `comment` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                  @Generated(
                                      comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                  )
                                  private Object someField;
                                                                
                                  // ... rest of generated code
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting methodMembers() {
        return ConfigurationSetting.builder()
                .setName("methodMembers")
                .setDescription("The annotation members to use for methods.")
                .setType(TypeName.get(GeneratedAnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .addExamples(ConfigurationExample.builder()
                        .setValue("WITHOUT_DATE")
                        .setDescription("The default value of the `methodMembers` configuration option is `WITHOUT_DATE`. Setting the option to `WITHOUT_DATE` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                      // ... some code
                                    }
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("ALL")
                        .setDescription("Changing the `methodMembers` configuration option to `ALL` outputs all annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                        // ... some code
                                    }
                                                                
                                     // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("NONE")
                        .setDescription("Changing the `methodMembers` configuration option to `NONE` outputs no annotation members.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated
                                    public void someMethod() {
                                        // ... some code
                                    }
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("VALUE")
                        .setDescription("Changing the `methodMembers` configuration option to `VALUE` outputs only the `value` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL"
                                    )
                                    public void someMethod() {
                                      // ... some code
                                    }
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("DATE")
                        .setDescription("Changing the `methodMembers` configuration option to `DATE` outputs only the `date` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        date = "<current_timestamp>"
                                    )
                                    public void someMethod() {
                                        // ... some code
                                    }
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("COMMENT")
                        .setDescription("Changing the `methodMembers` configuration option to `COMMENT` outputs only the `comment` member.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                        // ... some code
                                    }
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting classComment() {
        return ConfigurationSetting.builder()
                .setName("classComment")
                .setDescription("Sets the comment used for annotated classes.")
                .setType(ClassName.get(String.class))
                .setValue(DEFAULT_COMMENT)
                .addExamples(ConfigurationExample.builder()
                        .setValue("DO NOT MODIFY - automatically generated by YoSQL")
                        .setDescription("The default value of the `classComment` configuration option is `DO NOT MODIFY - automatically generated by YoSQL`. Setting the option to `PROCESSING_API` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                )
                                public class SomeRepository {
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("Hello World!")
                        .setDescription("Changing the `classComment` configuration option to `Hello World!` produces the following code:")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.Generated;
                                                                
                                @Generated(
                                    value = "YoSQL",
                                    date = "<current_timestamp>",
                                    comments = "Hello World!"
                                )
                                public class SomeRepository {
                                                                
                                    // ... rest of generated code (same as above)
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting fieldComment() {
        return ConfigurationSetting.builder()
                .setName("fieldComment")
                .setDescription("Sets the comment used for annotated fields.")
                .setType(ClassName.get(String.class))
                .setValue(DEFAULT_COMMENT)
                .addExamples(ConfigurationExample.builder()
                        .setValue("DO NOT MODIFY - automatically generated by YoSQL")
                        .setDescription("The default value of the `fieldComment` configuration option is `DO NOT MODIFY - automatically generated by YoSQL`. Setting the option to `DO NOT MODIFY - automatically generated by YoSQL` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("Hello World!")
                        .setDescription("Changing the `fieldComment` configuration option to `Hello World!` produces the following code:")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "Hello World!"
                                    )
                                    private Object someField;
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting methodComment() {
        return ConfigurationSetting.builder()
                .setName("methodComment")
                .setDescription("Sets the comment used for annotated methods.")
                .setType(ClassName.get(String.class))
                .setValue(DEFAULT_COMMENT)
                .addExamples(ConfigurationExample.builder()
                        .setValue("DO NOT MODIFY - automatically generated by YoSQL")
                        .setDescription("The default value of the `methodComment` configuration option is `DO NOT MODIFY - automatically generated by YoSQL`. Setting the option to `DO NOT MODIFY - automatically generated by YoSQL` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    public void someMethod() {
                                        // ... some code
                                    }
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("Hello World!")
                        .setDescription("Changing the `methodComment` configuration option to `Hello World!` produces the following code:")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "Hello World!"
                                    )
                                    public void someMethod() {
                                      // ... some code
                                    }
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting generatorName() {
        return ConfigurationSetting.builder()
                .setName("generatorName")
                .setDescription("The name of the code generator")
                .setType(ClassName.get(String.class))
                .setValue("YoSQL")
                .addExamples(ConfigurationExample.builder()
                        .setValue("YoSQL")
                        .setDescription("The default value of the `generatorName` configuration option is `YoSQL`. Setting the option to `YoSQL` therefore produces the same code generated as the default configuration.")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "YoSQL",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .addExamples(ConfigurationExample.builder()
                        .setValue("Hello World!")
                        .setDescription("Changing the `generatorName` configuration option to `Hello World!` produces the following code:")
                        .setResult("""
                                package com.example.persistence;
                                                                
                                import javax.annotation.processing.Generated;
                                                                
                                public class SomeRepository {
                                                                
                                    @Generated(
                                        value = "Hello World!",
                                        date = "<current_timestamp>",
                                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                                    )
                                    private Object someField;
                                                                
                                    // ... rest of generated code
                                                                
                                }""")
                        .build())
                .build();
    }

    private static ConfigurationSetting repositoryAnnotations() {
        return ConfigurationSetting.builder()
                .setName("repositoryAnnotations")
                .setDescription("The additional annotations to be placed on generated repository classes.")
                .setType(TypicalTypes.listOf(Annotation.class))
                .setValue(CodeBlock.builder().add("$T.of()", List.class).build())
                .setCliValue("")
                .setMavenValue("")
                .setMavenType(TypicalTypes.listOf(MAVEN_ANNOTATION_TYPE))
                .setGradleType(TypicalTypes.gradleContainerOf(GRADLE_ANNOTATION_TYPE))
                .build();
    }

    private static ConfigurationSetting constructorAnnotations() {
        return ConfigurationSetting.builder()
                .setName("constructorAnnotations")
                .setDescription("The additional annotations to be placed on generated constructors.")
                .setType(TypicalTypes.listOf(Annotation.class))
                .setValue(CodeBlock.builder().add("$T.of()", List.class).build())
                .setCliValue("")
                .setMavenValue("")
                .setMavenType(TypicalTypes.listOf(MAVEN_ANNOTATION_TYPE))
                .setGradleType(TypicalTypes.gradleContainerOf(GRADLE_ANNOTATION_TYPE))
                .build();
    }

    private static ConfigurationSetting methodAnnotations() {
        return ConfigurationSetting.builder()
                .setName("methodAnnotations")
                .setDescription("The additional annotations to be placed on generated methods.")
                .setType(TypicalTypes.listOf(Annotation.class))
                .setValue(CodeBlock.builder().add("$T.of()", List.class).build())
                .setCliValue("")
                .setMavenValue("")
                .setMavenType(TypicalTypes.listOf(MAVEN_ANNOTATION_TYPE))
                .setGradleType(TypicalTypes.gradleContainerOf(GRADLE_ANNOTATION_TYPE))
                .build();
    }

    private static TypeSpec mavenAnnotationSpecType() {
        return TypeSpec.classBuilder(ANNOTATION_SPEC)
                .addModifiers(Modifier.PUBLIC)
                .addField(mavenStringParameter(TYPE))
                .addField(mavenParameter(TypicalTypes.listOf(MAVEN_MEMBER_TYPE), MEMBERS))
                .addMethod(MethodSpec.methodBuilder(AS_ANNOTATION)
                        .addModifiers(Modifier.FINAL)
                        .returns(Annotation.class)
                        .addStatement(CodeBlock.builder()
                                .add("return $T.builder()", Annotation.class)
                                .add("$>\n.set$L($L)", upperCase(TYPE), TYPE)
                                .add("\n.addAll$L($T.ofNullable($L).flatMap($T::stream).map($T::$L).toList())",
                                        upperCase(MEMBERS), Stream.class, MEMBERS, Collection.class, MAVEN_MEMBER_TYPE, AS_ANNOTATION_MEMBER)
                                .add("\n.build()$<")
                                .build())
                        .build())
                .build();
    }

    private static TypeSpec mavenAnnotationMemberSpecType() {
        return TypeSpec.classBuilder(ANNOTATION_MEMBER_SPEC)
                .addModifiers(Modifier.PUBLIC)
                .addField(mavenStringParameter(TYPE, "java.lang.String"))
                .addField(mavenStringParameter(KEY))
                .addField(mavenStringParameter(VALUE))
                .addMethod(MethodSpec.methodBuilder(AS_ANNOTATION_MEMBER)
                        .addModifiers(Modifier.FINAL)
                        .returns(AnnotationMember.class)
                        .addStatement(CodeBlock.builder()
                                .add("return $T.builder()", AnnotationMember.class)
                                .add("$>\n.set$L($L)", upperCase(KEY), KEY)
                                .add("\n.set$L($L)", upperCase(VALUE), VALUE)
                                .add("\n.set$L($L)", upperCase(TYPE), TYPE)
                                .add("\n.build()$<")
                                .build())
                        .build())
                .build();
    }

    private static MethodSpec createMavenAnnotations() {
        return MethodSpec.methodBuilder("createAnnotations")
                .addModifiers(Modifier.FINAL)
                .returns(TypicalTypes.listOf(Annotation.class))
                .addParameter(ParameterSpec.builder(TypicalTypes.listOf(MAVEN_ANNOTATION_TYPE), "specs", Modifier.FINAL).build())
                .addStatement("return $T.ofNullable($L).flatMap($T::stream).map($T::$L).toList()",
                        Stream.class, "specs", Collection.class, MAVEN_ANNOTATION_TYPE, AS_ANNOTATION)
                .build();
    }

    private static TypeSpec gradleAnnotationSpecType() {
        return TypeSpec.classBuilder(ANNOTATION_SPEC)
                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                .addJavadoc("Configures a single Annotation.")
                .addSuperinterface(TypicalTypes.GRADLE_NAMED)
                .addMethod(gradleConstructor())
                .addMethod(gradleNamedProperty(GRADLE_MEMBER_TYPE, "get" + upperCase(MEMBERS), "The annotation members"))
                .addMethod(MethodSpec.methodBuilder(AS_ANNOTATION)
                        .addModifiers(Modifier.FINAL)
                        .returns(Annotation.class)
                        .addStatement(CodeBlock.builder()
                                .add("return $T.builder()", Annotation.class)
                                .add("$>\n.set$L(getName())", upperCase(TYPE))
                                .add("\n.addAll$L(get$L().stream().map($T::$L).toList())",
                                        upperCase(MEMBERS), upperCase(MEMBERS), GRADLE_MEMBER_TYPE, AS_ANNOTATION_MEMBER)
                                .add("\n.build()$<")
                                .build())
                        .build())
                .build();
    }

    private static TypeSpec gradleAnnotationMemberSpecType() {
        return TypeSpec.classBuilder(ANNOTATION_MEMBER_SPEC)
                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                .addJavadoc("Configures a single AnnotationMember.")
                .addSuperinterface(TypicalTypes.GRADLE_NAMED)
                .addMethod(gradleConstructor())
                .addMethod(gradleStringProperty("get" + upperCase(VALUE), "The value of the annotation member"))
                .addMethod(gradleStringProperty("get" + upperCase(TYPE), "The fully-qualified type of the annotation member"))
                .addMethod(MethodSpec.methodBuilder(AS_ANNOTATION_MEMBER)
                        .addModifiers(Modifier.FINAL)
                        .returns(AnnotationMember.class)
                        .addStatement(CodeBlock.builder()
                                .add("return $T.builder()", AnnotationMember.class)
                                .add("$>\n.set$L(getName())", upperCase(KEY))
                                .add("\n.set$L(get$L().get())", upperCase(VALUE), upperCase(VALUE))
                                .add("\n.set$L(get$L().getOrElse($S))", upperCase(TYPE), upperCase(TYPE), "java.lang.String")
                                .add("\n.build()$<")
                                .build())
                        .build())
                .build();
    }

    private static MethodSpec createGradleAnnotations() {
        return MethodSpec.methodBuilder("createAnnotations")
                .addModifiers(Modifier.FINAL)
                .returns(TypicalTypes.listOf(Annotation.class))
                .addParameter(ParameterSpec.builder(TypicalTypes.listOf(GRADLE_ANNOTATION_TYPE), "specs", Modifier.FINAL).build())
                .addStatement("return $T.ofNullable($L).flatMap($T::stream).map($T::$L).toList()",
                        Stream.class, "specs", Collection.class, GRADLE_ANNOTATION_TYPE, AS_ANNOTATION)
                .build();
    }

    private Annotations() {
        // data class
    }

}
