/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at http://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.models.meta.data;

import com.squareup.javapoet.TypeName;
import wtf.metio.yosql.internals.javapoet.TypicalTypes;
import wtf.metio.yosql.models.constants.configuration.AnnotationClass;
import wtf.metio.yosql.models.constants.configuration.AnnotationMembers;
import wtf.metio.yosql.models.meta.ConfigurationGroup;
import wtf.metio.yosql.models.meta.ConfigurationSetting;

public final class Annotations {

    public static final String DEFAULT_COMMENT = "DO NOT MODIFY - automatically generated by YoSQL";
    public static final AnnotationClass DEFAULT_ANNOTATION = AnnotationClass.PROCESSING_API;
    public static final AnnotationMembers DEFAULT_MEMBERS = AnnotationMembers.WITHOUT_DATE;
    
    public static ConfigurationGroup configurationGroup() {
        return ConfigurationGroup.builder()
                .setName(Annotations.class.getSimpleName())
                .setDescription("Configures how annotations are applied to the generated code.")
                .addSettings(annotateClasses())
                .addSettings(annotateFields())
                .addSettings(annotateMethods())
                .addSettings(classAnnotation())
                .addSettings(fieldAnnotation())
                .addSettings(methodAnnotation())
                .addSettings(classMembers())
                .addSettings(fieldMembers())
                .addSettings(methodMembers())
                .addSettings(classComment())
                .addSettings(fieldComment())
                .addSettings(methodComment())
                .addSettings(generatorName())
                .build();
    }

    private static ConfigurationSetting annotateClasses() {
        return ConfigurationSetting.builder()
                .setName("annotateClasses")
                .setDescription("Controls whether Generated annotations should be added to the generated classes.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.CLASSES)
                .build();
    }

    private static ConfigurationSetting annotateFields() {
        return ConfigurationSetting.builder()
                .setName("annotateFields")
                .setDescription("Controls whether Generated annotations should be added to the generated fields.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.FIELDS)
                .build();
    }

    private static ConfigurationSetting annotateMethods() {
        return ConfigurationSetting.builder()
                .setName("annotateMethods")
                .setDescription("Controls whether Generated annotations should be added to the generated methods.")
                .setType(TypeName.get(boolean.class))
                .setValue(false)
                .addTags(Tags.METHODS)
                .build();
    }

    private static ConfigurationSetting classAnnotation() {
        return ConfigurationSetting.builder()
                .setName("classAnnotation")
                .setDescription("The annotation API to use for classes.")
                .setType(TypeName.get(AnnotationClass.class))
                .setValue(DEFAULT_ANNOTATION)
                .build();
    }

    private static ConfigurationSetting fieldAnnotation() {
        return ConfigurationSetting.builder()
                .setName("fieldAnnotation")
                .setDescription("The annotation API to use for fields.")
                .setType(TypeName.get(AnnotationClass.class))
                .setValue(DEFAULT_ANNOTATION)
                .build();
    }

    private static ConfigurationSetting methodAnnotation() {
        return ConfigurationSetting.builder()
                .setName("methodAnnotation")
                .setDescription("The annotation API to use for methods.")
                .setType(TypeName.get(AnnotationClass.class))
                .setValue(DEFAULT_ANNOTATION)
                .build();
    }

    private static ConfigurationSetting classMembers() {
        return ConfigurationSetting.builder()
                .setName("classMembers")
                .setDescription("The annotation members to use for classes.")
                .setType(TypeName.get(AnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .build();
    }

    private static ConfigurationSetting fieldMembers() {
        return ConfigurationSetting.builder()
                .setName("fieldMembers")
                .setDescription("The annotation members to use for fields.")
                .setType(TypeName.get(AnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .build();
    }

    private static ConfigurationSetting methodMembers() {
        return ConfigurationSetting.builder()
                .setName("methodMembers")
                .setDescription("The annotation members to use for methods.")
                .setType(TypeName.get(AnnotationMembers.class))
                .setValue(DEFAULT_MEMBERS)
                .build();
    }

    private static ConfigurationSetting classComment() {
        return ConfigurationSetting.builder()
                .setName("classComment")
                .setDescription("Sets the comment used for annotated classes.")
                .setType(TypicalTypes.STRING)
                .setValue(DEFAULT_COMMENT)
                .build();
    }

    private static ConfigurationSetting fieldComment() {
        return ConfigurationSetting.builder()
                .setName("fieldComment")
                .setDescription("Sets the comment used for annotated fields.")
                .setType(TypicalTypes.STRING)
                .setValue(DEFAULT_COMMENT)
                .build();
    }

    private static ConfigurationSetting methodComment() {
        return ConfigurationSetting.builder()
                .setName("methodComment")
                .setDescription("Sets the comment used for annotated methods.")
                .setType(TypicalTypes.STRING)
                .setValue(DEFAULT_COMMENT)
                .build();
    }

    private static ConfigurationSetting generatorName() {
        return ConfigurationSetting.builder()
                .setName("generatorName")
                .setDescription("The name of the code generator")
                .setType(TypeName.get(String.class))
                .setValue("YoSQL")
                .build();
    }

    private Annotations() {
        // data class
    }

}
