/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.dao;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import wtf.metio.yosql.internals.testing.configs.JavaConfigurations;

@DisplayName("DefaultConstructorGenerator")
final class DefaultConstructorGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults extends ConstructorTCK {

        @Override
        ConstructorGenerator generator() {
            return DaoObjectMother.constructorGenerator(JavaConfigurations.defaults());
        }

        @Override
        String forRepositoryExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """;
        }

        @Override
        String forRepositoryWithGivenConnectionsExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public Constructor() {
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """;
        }

        @Override
        String forRepositoryWithCustomConverterExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.item = new com.example.persistence.converter.ToItemConverter();
                    }
                    """;
        }

        @Override
        String forRepositoryWithMultipleStatementsAndMixedConverterExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.item = new com.example.persistence.converter.ToItemConverter();
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """;
        }

    }

}
