/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.dao;

import wtf.metio.yosql.codegen.YoSqlVersion;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import wtf.metio.yosql.internals.testing.configs.RepositoriesConfigurations;

@DisplayName("DefaultConstructorGenerator")
final class DefaultConstructorGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults extends ConstructorTCK {

        @Override
        ConstructorGenerator generator() {
            return DaoObjectMother.constructorGenerator();
        }

        @Override
        ConstructorGenerator generatorWithoutConnectionOverloads() {
            return DaoObjectMother.constructorGenerator(                    RepositoriesConfigurations.withoutConnectionOverloads());
        }

        @Override
        String forRepositoryExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "wtf.metio.yosql",
                        comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """.replace("${version}", YoSqlVersion.VERSION);
        }

        @Override
        String forRepositoryWithGivenConnectionsExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "wtf.metio.yosql",
                        comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                    )
                    public Constructor() {
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """.replace("${version}", YoSqlVersion.VERSION);
        }

        @Override
        String forRepositoryWithCustomConverterExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "wtf.metio.yosql",
                        comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.item = new com.example.persistence.converter.ToItemConverter();
                    }
                    """.replace("${version}", YoSqlVersion.VERSION);
        }

        @Override
        String forRepositoryWithMultipleStatementsAndMixedConverterExpectation() {
            return """
                    /**
                     * Creates a new repository reading from the given data source.
                     */
                    @javax.annotation.processing.Generated(
                        value = "wtf.metio.yosql",
                        comments = "generated by YoSQL ${version} - do not modify, this file is rewritten on every build"
                    )
                    public Constructor(final javax.sql.DataSource dataSource) {
                      this.dataSource = dataSource;
                      this.item = new com.example.persistence.converter.ToItemConverter();
                      this.toMap = new com.example.persistence.converter.ToMapConverter();
                    }
                    """.replace("${version}", YoSqlVersion.VERSION);
        }

    }

}
