/*
 * This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
 * directory of this distribution and at https://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
 * including this file, may be copied, modified, propagated, or distributed except according to the terms contained
 * in the LICENSE file.
 */

package wtf.metio.yosql.codegen.dao;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import wtf.metio.yosql.testing.configs.JavaConfigurations;

@DisplayName("DefaultFieldsGenerator")
final class DefaultFieldsGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults extends FieldsGeneratorTCK {

        @Override
        FieldsGenerator generator() {
            return DaoObjectMother.fieldsGenerator(JavaConfigurations.defaults());
        }

        @Override
        String staticInitializerExpectation() {
            return """
                    QUERY_DATA_INDEX.put("test", new int[] { 0 });
                    QUERY_DATA_INDEX.put("id", new int[] { 1 });
                    """;
        }

        @Override
        String asFieldsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndMixedConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 11 configuration")
    class Java11 extends FieldsGeneratorTCK {

        @Override
        FieldsGenerator generator() {
            return DaoObjectMother.fieldsGenerator(JavaConfigurations.java11());
        }

        @Override
        String staticInitializerExpectation() {
            return """
                    QUERY_DATA_INDEX.put("test", new int[] { 0 });
                    QUERY_DATA_INDEX.put("id", new int[] { 1 });
                    """;
        }

        @Override
        String asFieldsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndMixedConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = "SELECT raw FROM table WHERE test = ? AND id = ?;";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 14 configuration")
    class Java14 extends FieldsGeneratorTCK {

        @Override
        FieldsGenerator generator() {
            return DaoObjectMother.fieldsGenerator(JavaConfigurations.java14());
        }

        @Override
        String staticInitializerExpectation() {
            return """
                    QUERY_DATA_INDEX.put("test", new int[] { 0 });
                    QUERY_DATA_INDEX.put("id", new int[] { 1 });
                    """;
        }

        @Override
        String asFieldsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndMixedConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

    }

    @Nested
    @DisplayName("using Java 16 configuration")
    class Java16 extends FieldsGeneratorTCK {

        @Override
        FieldsGenerator generator() {
            return DaoObjectMother.fieldsGenerator(JavaConfigurations.java16());
        }

        @Override
        String staticInitializerExpectation() {
            return """
                    QUERY_DATA_INDEX.put("test", new int[] { 0 });
                    QUERY_DATA_INDEX.put("id", new int[] { 1 });
                    """;
        }

        @Override
        String asFieldsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndMixedConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>data/queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

    }

}
