/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.dao;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import wtf.metio.yosql.codegen.exceptions.DuplicateConverterAliasException;
import wtf.metio.yosql.internals.testing.configs.RepositoriesConfigurations;
import wtf.metio.yosql.internals.testing.configs.SqlConfigurations;
import wtf.metio.yosql.models.configuration.ResultRowConverter;
import wtf.metio.yosql.models.immutables.SqlConfiguration;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DisplayName("DefaultFieldsGenerator")
final class DefaultFieldsGeneratorTest {

    @Nested
    @DisplayName("using default configuration")
    class Defaults extends FieldsGeneratorTCK {

        @Override
        FieldsGenerator generator() {
            return DaoObjectMother.fieldsGenerator();
        }

        @Override
        FieldsGenerator generatorWithoutConnectionOverloads() {
            return DaoObjectMother.fieldsGenerator(                    RepositoriesConfigurations.withoutConnectionOverloads());
        }

        @Override
        String staticInitializerExpectation() {
            return """
                    QUERY_DATA_INDEX.put("test", new int[] { 0 });
                    QUERY_DATA_INDEX.put("id", new int[] { 1 });
                    """;
        }

        @Override
        String asFieldsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndCustomConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                    """;
        }

        @Override
        String asFieldsWithMultipleStatementsAndMixedConverterExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final javax.sql.DataSource dataSource;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToItemConverter item;
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

        @Override
        String asFieldsWithGivenConnectionsExpectations() {
            return """
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(com.example.persistence.DataRepository.class.getName());
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA_RAW = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    /**
                     * Generated based on the following file:
                     * <ul>
                     * <li>queryData.sql</li>
                     * </ul>
                     */
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.lang.String QUERY_DATA = ""\"
                        SELECT raw FROM table WHERE test = ? AND id = ?;""\";
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private static final java.util.Map<java.lang.String, int[]> QUERY_DATA_INDEX = new java.util.HashMap<>(2);
                                        
                    @javax.annotation.processing.Generated(
                        value = "YoSQL",
                        comments = "DO NOT MODIFY - automatically generated by YoSQL"
                    )
                    private final com.example.persistence.converter.ToMapConverter toMap;
                    """;
        }

    }

    @Test
    @DisplayName("two converter classes sharing a simple name would share a field")
    void rejectsCollidingConverterAliases() {
        final var generator = DaoObjectMother.fieldsGenerator();
        final var statements = List.of(
                SqlConfigurations.sqlStatement(SqlConfiguration.copyOf(SqlConfigurations.sqlConfiguration())
                        .withResultRowConverter(converter("orders.ToItemConverter"))),
                SqlConfigurations.sqlStatement(SqlConfiguration.copyOf(SqlConfigurations.sqlConfiguration())
                        .withResultRowConverter(converter("catalog.ToItemConverter"))));

        final var exception = assertThrows(DuplicateConverterAliasException.class,
                () -> generator.asFields(statements));

        assertAll(
                () -> assertTrue(exception.getMessage().contains("orders.ToItemConverter")),
                () -> assertTrue(exception.getMessage().contains("catalog.ToItemConverter")),
                () -> assertTrue(exception.getMessage().contains("toItemConverter"))
        );
    }

    private static ResultRowConverter converter(final String converterType) {
        return ResultRowConverter.builder()
                .setAlias("toItemConverter")
                .setConverterType(converterType)
                .setMethodName("asUserType")
                .setResultType("com.example.domain.Item")
                .build();
    }

}
