java_library(
    name = "i18n",
    srcs = [
        "CliEvents.java",
        "Commands.java",
    ],
    visibility = [
        "//yosql-cli/src/main/java/wtf/metio/yosql/cli:__pkg__",
        "//yosql-cli/src/main/java/wtf/metio/yosql/cli/dagger:__pkg__",
    ],
    deps = [
        "@maven//:ch_qos_cal10n_cal10n_api",
    ],
)
