# This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
# directory of this distribution and at http://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
# including this file, may be copied, modified, propagated, or distributed except according to the terms contained
# in the LICENSE file.

java_library(
    name = "i18n",
    srcs = [
        "CliEvents.java",
        "Commands.java",
    ],
    visibility = [
        "//yosql-cli/src/main/java/wtf/metio/yosql/cli:__pkg__",
        "//yosql-cli/src/main/java/wtf/metio/yosql/cli/dagger:__pkg__",
    ],
    deps = [
        "@maven//:ch_qos_cal10n_cal10n_api",
    ],
)
