java_library(
    name = "parser",
    srcs = ["FileSetResolver.java"],
    deps = [
        "//yosql-core/src/main/java/wtf/metio/yosql/model:errors",
        "//yosql-core/src/main/java/wtf/metio/yosql/parser:io",
        "@maven//:javax_inject_javax_inject",
        "@maven//:org_apache_maven_maven_model",
        "@maven//:org_apache_maven_shared_maven_shared_utils",
    ],
)
