# This file is part of yosql. It is subject to the license terms in the LICENSE file found in the top-level
# directory of this distribution and at http://creativecommons.org/publicdomain/zero/1.0/. No part of yosql,
# including this file, may be copied, modified, propagated, or distributed except according to the terms contained
# in the LICENSE file.

java_library(
    name = "parser",
    srcs = ["FileSetResolver.java"],
    deps = [
        "//yosql-core/src/main/java/wtf/metio/yosql/model:errors",
        "//yosql-core/src/main/java/wtf/metio/yosql/parser:io",
        "@maven//:javax_inject_javax_inject",
        "@maven//:org_apache_maven_maven_model",
        "@maven//:org_apache_maven_shared_maven_shared_utils",
    ],
)
