# SPDX-FileCopyrightText: The yosql Authors
# SPDX-License-Identifier: 0BSD

baseURL = "https://yosql.projects.metio.wtf/"
locale = "en"
theme = "metio"
title = "YoSQL"

pygmentsUseClasses = true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[outputs]
home = ["HTML", "RSS", "ATOM", "HUMANS", "FOAF"]
section = ["HTML", "RSS", "ATOM"]
term = ["HTML", "RSS", "ATOM"]

[params]
mainSections = ["installation", "tooling", "frameworks", "editors", "configuration", "integration", "logging", "persistence", "benchmarks", "project", "sql"]
author = "metio.wtf"
github = "metio/yosql"
work = "yosql.projects.metio.wtf"
description = "Write more SQL"
licenseName = "0BSD"
licenseURL = "https://spdx.org/licenses/0BSD.html"

[security.funcs]
getenv = ['^HUGO_', '^YOSQL_']
