baseURL = "https://yosql.projects.metio.wtf/"
languageCode = "en"
theme = "metio"
title = "YoSQL - write more SQL"

pygmentsUseClasses = true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[outputs]
home = ["HTML", "RSS", "ATOM", "HUMANS", "FOAF"]
section = ["HTML", "RSS", "ATOM"]
term = ["HTML", "RSS", "ATOM"]

[params]
mainSections = ["tooling", "configuration", "integration", "logging", "persistence", "benchmarks", "project", "sql"]
author = "metio.wtf"
email = "https://metio.groups.io/g/yosql/topics"
matrix = "#yosql:matrix.org"
github = "metio/yosql"
work = "yosql.projects.metio.wtf"
calendar = "https://metio.groups.io/g/yosql/calendar"
description = "Write more SQL"
