/*
 * SPDX-FileCopyrightText: The yosql Authors
 * SPDX-License-Identifier: 0BSD
 */

package wtf.metio.yosql.codegen.logging;

import org.junit.jupiter.api.DisplayName;
import wtf.metio.yosql.codegen.blocks.BlocksObjectMother;

@DisplayName("Log4jLoggingGenerator")
final class Log4jLoggingGeneratorTest implements LoggingGeneratorTCK {

    @Override
    public LoggingGenerator generator() {
        return new Log4jLoggingGenerator(BlocksObjectMother.fields());
    }

    @Override
    public String loggerExpectation() {
        return """
                @javax.annotation.processing.Generated(
                    value = "YoSQL",
                    comments = "DO NOT MODIFY - automatically generated by YoSQL"
                )
                private static final org.apache.logging.log4j.Logger LOG = org.apache.logging.log4j.LogManager.getLogger(com.example.TestRepository.class);
                """;
    }

    @Override
    public String enteringExpectation() {
        return """
                LOG.debug(() -> java.lang.String.format("Entering [%s#%s]", "TestRepository", "queryData"));
                """;
    }

    @Override
    public String executingQueryExpectation() {
        return """
                LOG.info(() -> java.lang.String.format("Executing query [%s]", executedQuery));
                """;
    }

    @Override
    public String queryPickedExpectation() {
        return """
                LOG.debug(() -> java.lang.String.format("Picked query [%s]", "queryData"));
                """;
    }

    @Override
    public String indexPickedExpectation() {
        return """
                LOG.debug(() -> java.lang.String.format("Picked index [%s]", "queryData"));
                """;
    }

    @Override
    public String shouldLogExpectation() {
        return """
                LOG.isEnabled(org.apache.logging.log4j.Level.INFO)""";
    }

    @Override
    public String vendorDetectedExpectation() {
        return """
                LOG.info(() -> java.lang.String.format("Detected database vendor [%s]", databaseProductName));
                """;
    }

    @Override
    public String vendorQueryPickedExpectation() {
        return """
                LOG.debug(() -> java.lang.String.format("Picked query [%s]", "queryData"));
                """;
    }

    @Override
    public String vendorIndexPickedExpectation() {
        return """
                LOG.debug(() -> java.lang.String.format("Picked index [%s]", "queryData"));
                """;
    }

    @Override
    public boolean isEnabledExpectation() {
        return true;
    }

}
