name: Run Benchmarks
on:
  release:
    types: [released]
env:
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: temurin
jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        benchmark: [codegen, dao]
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: last_release
        name: Fetch last release info
        run: echo "tag=$(gh release view --json tagName --jq '.tagName')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: java
        name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven
      - id: run-benchmark
        name: Run Benchmark [${{ matrix.benchmark }}]
        run: mvn --batch-mode --projects yosql-benchmarks/yosql-benchmarks-${{ matrix.benchmark }} --also-make --activate-profiles benchmarks verify --define org.slf4j.simpleLogger.log.yosql=warn --define skipTests 2>&1 1> build.log
      - id: copy-results
        name: Copy ${{ matrix.benchmark }} Results
        run: cp --force ./yosql-benchmarks/yosql-benchmarks-${{ matrix.benchmark }}/target/benchmark/yosql-benchmarks-${{ matrix.benchmark }}.json ./yosql-website/content/benchmarks/results/yosql-benchmarks-${{ matrix.benchmark }}-${{ steps.last_release.outputs.tag }}.json
      - id: replace-results
        name: Replace CURRENT ${{ matrix.benchmark }} Results
        run: cp --force ./yosql-benchmarks/yosql-benchmarks-${{ matrix.benchmark }}/target/benchmark/yosql-benchmarks-${{ matrix.benchmark }}.json ./yosql-website/content/benchmarks/results/yosql-benchmarks-${{ matrix.benchmark }}-CURRENT.json
      - id: push
        name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update benchmark data for ${{ steps.last_release.outputs.tag }}
          file_pattern: yosql-website/*.json
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update benchmarks for latest release
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update benchmarks for latest release
          body: ${{ steps.gwu.outputs.version-information }}
          labels: |
            Release :: Ignore
            Benchmarks :: CodeGen
            Benchmarks :: DAO
            Priority :: Low
            Type :: Task
          assignees: sebhoss
          draft: false
          base: main
          branch: update-benchmarks
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        with:
          token: ${{ secrets.PAT }}
