name: Build Project
on:
  push:
    branches: [ main ]
    paths:
      - yosql-codegen/**
      - yosql-converters/**
      - yosql-dao/**
      - yosql-internals/**
      - yosql-logging/**
      - yosql-models/**
      - yosql-testing/**
      - yosql-tooling/**
  pull_request:
    branches: [ main ]
    paths:
      - yosql-codegen/**
      - yosql-converters/**
      - yosql-dao/**
      - yosql-internals/**
      - yosql-logging/**
      - yosql-models/**
      - yosql-testing/**
      - yosql-tooling/**
env:
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: adopt
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v3
      - id: java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
      - id: cache
        name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: maven
        name: Maven Tooling
        run: mvn --batch-mode install
      - id: gradle
        name: Gradle Tooling
        run: cd ./yosql-examples/yosql-examples-gradle/ && ./gradlew build
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        benchmark: [codegen, jdbc]
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v3
      - id: java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
      - id: cache
        name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: run-benchmark
        name: Run Benchmark [${{ matrix.benchmark }}]
        run: mvn --batch-mode --projects yosql-benchmarks/yosql-benchmarks-${{ matrix.benchmark }} --also-make --activate-profiles benchmarks verify -Dorg.slf4j.simpleLogger.log.yosql=warn -DskipTests 2>&1 1> build.log
      - id: upload-benchmark
        name: Upload Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-${{ matrix.benchmark }}
          path: ./yosql-benchmarks/yosql-benchmarks-${{ matrix.benchmark }}/target/benchmark/yosql-benchmarks-${{ matrix.benchmark }}.json
