name: Pull Requests
on:
  pull_request:
    branches: [ main ]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v2
      - id: java
        name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
          java-package: jdk
          architecture: x64
      - id: cache
        name: Cache Maven Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: install
        name: Install Project
        run: mvn --batch-mode --settings $GITHUB_WORKSPACE/build/settings.xml install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
