name: Qodana Scan
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/qodana.yml
      - pom.xml
      - yosql-benchmarks/**
      - yosql-codegen/**
      - yosql-examples/**
      - yosql-internals/**
      - yosql-models/**
      - yosql-tooling/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/qodana.yml
      - pom.xml
      - yosql-benchmarks/**
      - yosql-codegen/**
      - yosql-examples/**
      - yosql-internals/**
      - yosql-models/**
      - yosql-tooling/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required in order to get all tags
      - id: qodana
        name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.1.1
