name: Update Gradle Wrapper
on:
  schedule:
    - cron: 0 2 3 * *
env:
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: temurin
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v3
      - id: java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
      - id: cache
        name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: maven
        name: Maven Tooling
        run: mvn --batch-mode install
      - name: update yosql-tooling-gradle
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          paths: yosql-tooling/yosql-tooling-gradle/**
      - name: update yosql-examples-gradle
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          paths: yosql-examples/yosql-examples-gradle/**
