name: Update Parent
on:
  schedule:
    - cron: 0 1 3 * *
env:
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: temurin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven
      - name: Update parent
        run: mvn --batch-mode --define generateBackupPoms=false versions:update-parent
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update parent to latest version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update parent to latest version
          body: |
            `mvn --batch-mode versions:update-parent -DgenerateBackupPoms=false`
          labels: |
            Build :: Maven
            Priority :: Low
            Type :: Task
          assignees: sebhoss
          draft: false
          base: main
          branch: update-parent
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        with:
          token: ${{ secrets.PAT }}
