name: Update Gradle Wrapper
on:
  schedule:
    - cron: 0 3 3 * *
env:
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: temurin
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v4
      - id: java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven
      - id: maven
        name: Maven Tooling
        run: mvn --batch-mode install --define skipTests
      - id: gwu
        name: yosql-tooling-gradle
        uses: EdwarDDay/upgrade-gradle-action@v1
        with:
          working-directory: yosql-tooling/yosql-tooling-gradle
          distribution-type: all
      - name: yosql-examples-gradle
        uses: EdwarDDay/upgrade-gradle-action@v1
        with:
          working-directory: yosql-examples/yosql-examples-gradle
          distribution-type: all
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update gradle-wrapper to latest version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update gradle-wrapper to latest version
          body: ${{ steps.gwu.outputs.version-information }}
          labels: |
            Build :: Gradle
            Priority :: Low
            Type :: Task
          assignees: sebhoss
          draft: false
          base: main
          branch: update-gradle-wrapper
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        with:
          token: ${{ secrets.PAT }}
