name: Publish Website
on:
  push:
    branches:
      - main
    paths:
      - yosql-website/**
env:
  PROJECT_URL: yosql.projects.metio.wtf
  JAVA_VERSION: 17
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: adopt
jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required in order to get all tags
      - id: hugo
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - id: java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          architecture: ${{ env.JAVA_ARCH }}
          distribution: ${{ env.JAVA_DISTRO }}
      - id: cache
        name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: previous
        name: Get Last Release
        run: echo "::set-output name=version::$(git describe --abbrev=0 --tags)"
      - name: Set release version
        run: mvn --batch-mode versions:set --define newVersion=${{ steps.previous.outputs.version }} --define generateBackupPoms=false
      - id: create-documentation
        name: Create Documentation
        run: mvn --batch-mode --projects yosql-website --also-make install --define skipTests
      - id: website
        name: Build Website
        run: hugo --minify --printI18nWarnings --printPathWarnings --printUnusedTemplates --source yosql-website
        env:
          YOSQL_RELEASE: ${{ steps.previous.outputs.version }}
      - id: htmltest
        name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: ./yosql-website/htmltest.yml
      - id: deploy
        name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./yosql-website/public
          force_orphan: true
          cname: ${{ env.PROJECT_URL }}
