name: Publish Website
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/website.yml
      - yosql-website/**
env:
  JAVA_VERSION: 17
  PROJECT_URL: yosql.projects.metio.wtf
jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # required in order to get all tags
      - id: hugo
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
      - id: graal
        name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven
      - id: previous
        name: Get Last Release
        run: echo "version=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
      - name: Set release version
        run: mvn --batch-mode --define newVersion=${{ steps.previous.outputs.version }} --define generateBackupPoms=false versions:set
      - id: create-documentation
        name: Create Documentation
        run: mvn --batch-mode --projects yosql-website --also-make --define skipTests install
      - id: website
        name: Build Website
        run: hugo --minify --printI18nWarnings --printPathWarnings --printUnusedTemplates --source yosql-website
        env:
          YOSQL_RELEASE: ${{ steps.previous.outputs.version }}
      - id: htmltest
        name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: ./yosql-website/htmltest.yml
      - id: deploy
        name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./yosql-website/public
          force_orphan: true
          cname: ${{ env.PROJECT_URL }}
